import { prisma } from "../../db/prisma";

type TxLike = { $queryRaw<T = unknown>(...args: any[]): Promise<T> };

type MergeCount = { inserted: number; updated: number };
type GenParams = { period: string; application_id: string; createdBy: string };

/**
 * DIVISION USER:
 * - Sumber: TB_M_AUTH_MAPPING (NOREG valid)
 * - Step: INSERT/UPSERT ke TB_R_WORKFLOW (SEQ_NO = 1) -> MERGE ke TB_R_UAR_DIVISION_USER
 */
async function mergeDivisionUserTx(tx: TxLike, p: GenParams): Promise<MergeCount> {
  const rows = await tx.$queryRaw<{ inserted: number; updated: number }[]>`
DECLARE @PERIOD_RAW NVARCHAR(30) = ${p.period};
DECLARE @APP_ID     NVARCHAR(50) = ${p.application_id};
DECLARE @CREATED_BY VARCHAR(50)  = ${p.createdBy};
-- const 
-- =========================
-- Normalisasi periode UAR => YYYYMM
-- =========================
DECLARE @UAR_PERIOD CHAR(6);
IF @PERIOD_RAW LIKE '[0-9][0-9][0-9][0-9][0-9][0-9]'
BEGIN
  SET @UAR_PERIOD = @PERIOD_RAW;
END
ELSE
BEGIN
  DECLARE @RUN_DATE DATE = TRY_CONVERT(DATE, @PERIOD_RAW, 126);
  IF @RUN_DATE IS NULL SET @RUN_DATE = TRY_CONVERT(DATE, @PERIOD_RAW);
  IF @RUN_DATE IS NULL THROW 50000, 'Invalid period. Use YYYYMM or ISO date (YYYY-MM-DD).', 1;
  SET @UAR_PERIOD = LEFT(CONVERT(CHAR(8), @RUN_DATE, 112), 6);
END
DECLARE @UYM CHAR(4) = RIGHT(@UAR_PERIOD, 4);

-- =========================
-- Konfigurasi dari TB_M_SYSTEM
-- =========================
DECLARE @REVIEW_LEAD_DAYS INT =
  TRY_CONVERT(INT, (
    SELECT TOP 1 VALUE_NUM
    FROM TB_M_SYSTEM
    WHERE SYSTEM_TYPE = 'config' AND SYSTEM_CD = 'REVIEW_LEAD_DAYS'
    ORDER BY VALID_FROM_DT DESC, CREATED_DT DESC
  ));
IF @REVIEW_LEAD_DAYS IS NULL SET @REVIEW_LEAD_DAYS = 3;

DECLARE @DPH_POSITION_CODES NVARCHAR(4000) =
  (SELECT TOP 1 VALUE_TEXT
   FROM TB_M_SYSTEM
   WHERE SYSTEM_TYPE = 'config' AND SYSTEM_CD = 'DPH_POSITION_CODES'
   ORDER BY VALID_FROM_DT DESC, CREATED_DT DESC);

-- split daftar position code DpH
IF OBJECT_ID('tempdb..#DPH_CODES') IS NOT NULL DROP TABLE #DPH_CODES;
SELECT LTRIM(RTRIM(value)) AS CODE
INTO #DPH_CODES
FROM STRING_SPLIT(COALESCE(@DPH_POSITION_CODES, ''), ',')
WHERE LTRIM(RTRIM(value)) <> '';

-- =========================
-- Sumber data: AUTH_MAPPING + EMPLOYEE (join NOREG)
-- =========================
IF OBJECT_ID('tempdb..#src_div') IS NOT NULL DROP TABLE #src_div;

SELECT
  @UAR_PERIOD AS UAR_PERIOD,
  CONCAT('UAR_', @UYM, '_', am.APPLICATION_ID) AS UAR_ID,
  am.USERNAME,
  am.ROLE_ID,
  am.APPLICATION_ID,
  emp.DIVISION_ID AS DIVISION_ID,
  emp.DEPARTMENT_ID AS DEPARTMENT_ID,
  NULLIF(LTRIM(RTRIM(am.NOREG)), '') AS NOREG,
  LTRIM(RTRIM(CONCAT(COALESCE(am.FIRST_NAME,''),' ',COALESCE(am.LAST_NAME,'')))) AS NAME,
  emp.POSITION_NAME AS POSITION_NAME,
  emp.SECTION_ID AS SECTION_ID,
  emp.DEPARTMENT_ID AS EMP_DEPT_ID
INTO #src_div
FROM TB_M_AUTH_MAPPING am
JOIN TB_M_APPLICATION  app ON app.APPLICATION_ID = am.APPLICATION_ID
JOIN TB_M_EMPLOYEE     emp ON emp.NOREG = am.NOREG
WHERE am.APPLICATION_ID = @APP_ID
  AND LTRIM(RTRIM(COALESCE(am.NOREG, ''))) <> ''
  AND REPLACE(LTRIM(RTRIM(am.NOREG)), '0', '') <> '';

-- =========================
-- Reviewer (DpH) per DEPARTMENT_ID (dari TB_M_EMPLOYEE)
-- =========================
IF OBJECT_ID('tempdb..#dept_reviewer') IS NOT NULL DROP TABLE #dept_reviewer;

;WITH pool AS (
  SELECT
    e.DEPARTMENT_ID,
    e.NOREG,
    e.PERSONNEL_NAME,
    e.POSITION_CODE,
    e.POSITION_LEVEL,
    e.VALID_FROM, e.VALID_TO,
    CASE WHEN EXISTS (SELECT 1 FROM #DPH_CODES d WHERE d.CODE = e.POSITION_CODE) THEN 1 ELSE 0 END AS IS_DPH
  FROM TB_M_EMPLOYEE e
),
ranked AS (
  SELECT
    p.*,
    ROW_NUMBER() OVER (
      PARTITION BY p.DEPARTMENT_ID
      ORDER BY
        p.IS_DPH DESC,
        CASE WHEN p.VALID_TO IS NULL OR p.VALID_TO >= GETDATE() THEN 0 ELSE 1 END,
        ISNULL(p.POSITION_LEVEL, 0) DESC,
        ISNULL(p.VALID_FROM, '1900-01-01') DESC
    ) AS rn
  FROM pool p
)
SELECT
  DEPARTMENT_ID,
  NOREG AS REVIEWER_NOREG,
  PERSONNEL_NAME AS REVIEWER_NAME
INTO #dept_reviewer
FROM ranked
WHERE rn = 1;

-- =========================
-- Approver Divisi dari TB_M_EMPLOYEE (bukan TB_H_EMPLOYEE)
-- Prioritas: POSITION_CODE ∈ DVH_POSITION_CODES -> aktif -> POSITION_LEVEL tertinggi
-- =========================
IF OBJECT_ID('tempdb..#DVH_CODES') IS NOT NULL DROP TABLE #DVH_CODES;
SELECT LTRIM(RTRIM(value)) AS CODE
INTO #DVH_CODES
FROM STRING_SPLIT(COALESCE(
  (SELECT TOP 1 VALUE_TEXT
   FROM TB_M_SYSTEM
   WHERE SYSTEM_TYPE='config' AND SYSTEM_CD='DVH_POSITION_CODES'
   ORDER BY VALID_FROM_DT DESC, CREATED_DT DESC), ''), ',')
WHERE LTRIM(RTRIM(value)) <> '';

IF OBJECT_ID('tempdb..#div_approver') IS NOT NULL DROP TABLE #div_approver;

;WITH pool2 AS (
  SELECT
    LTRIM(RTRIM(e.DIVISION_ID)) AS DIVISION_ID,
    e.NOREG          AS APPROVER_NOREG,
    e.PERSONNEL_NAME AS APPROVER_NAME,
    CASE WHEN EXISTS (SELECT 1 FROM #DVH_CODES c WHERE c.CODE = e.POSITION_CODE) THEN 1 ELSE 0 END AS IS_DVH,
    e.POSITION_LEVEL,
    e.VALID_FROM, e.VALID_TO
  FROM TB_M_EMPLOYEE e
  WHERE e.DIVISION_ID IS NOT NULL
),
ranked2 AS (
  SELECT
    p.*,
    ROW_NUMBER() OVER (
      PARTITION BY p.DIVISION_ID
      ORDER BY
        p.IS_DVH DESC,
        CASE WHEN p.VALID_TO IS NULL OR p.VALID_TO >= GETDATE() THEN 0 ELSE 1 END,
        ISNULL(p.POSITION_LEVEL,0) DESC,
        ISNULL(p.VALID_FROM,'1900-01-01') DESC
    ) rn
  FROM pool2 p
)
SELECT DIVISION_ID, APPROVER_NOREG, APPROVER_NAME
INTO #div_approver
FROM ranked2
WHERE rn = 1;

-- =========================
-- (1) UPSERT WORKFLOW SEQ 1 (Division) + approver (fallback ke DpH)
-- =========================
MERGE TB_R_WORKFLOW AS wf
USING (
  SELECT
    d.UAR_ID,
    d.DIVISION_ID,
    d.DEPARTMENT_ID,
    COALESCE(a.APPROVER_NOREG, r.REVIEWER_NOREG) AS APPROVER_NOREG,
    COALESCE(a.APPROVER_NAME, r.REVIEWER_NAME)   AS APPROVER_NAME
  FROM #src_div d
  LEFT JOIN #div_approver a
    ON LTRIM(RTRIM(a.DIVISION_ID)) = LTRIM(RTRIM(d.DIVISION_ID))
  LEFT JOIN #dept_reviewer r
    ON r.DEPARTMENT_ID = d.DEPARTMENT_ID
) AS x
ON (wf.UAR_ID = x.UAR_ID AND wf.SEQ_NO = 1)
WHEN NOT MATCHED THEN
  INSERT (
    UAR_ID, SEQ_NO,
    DIVISION_ID, DEPARTMENT_ID,
    APPROVAL_CD, APPROVAL_DESC,
    APPROVER_NOREG, APPROVER_NAME,
    PLAN_APPROVED_DT, APPROVED_BY, APPROVED_DT,
    IS_APPROVED, IS_REJECTED,
    CREATED_BY, CREATED_DT
  )
  VALUES (
    x.UAR_ID, 1,
    x.DIVISION_ID, x.DEPARTMENT_ID,
    1, 'Division Approval',
    x.APPROVER_NOREG, x.APPROVER_NAME,
    NULL, NULL, NULL,
    0, 0,
    @CREATED_BY, GETDATE()
  )
WHEN MATCHED THEN
  UPDATE SET
    wf.DIVISION_ID    = x.DIVISION_ID,
    wf.DEPARTMENT_ID  = x.DEPARTMENT_ID,
    wf.APPROVER_NOREG = x.APPROVER_NOREG,
    wf.APPROVER_NAME  = x.APPROVER_NAME,
    wf.CHANGED_BY     = @CREATED_BY,
    wf.CHANGED_DT     = GETDATE();

-- =========================
-- (2) MERGE ke TB_R_UAR_DIVISION_USER (+ POSITION_NAME, SECTION_ID, Reviewer)
-- =========================
DECLARE @chg TABLE (action NVARCHAR(10));

MERGE TB_R_UAR_DIVISION_USER AS tgt
USING (
  SELECT
    s.*,
    r.REVIEWER_NOREG,
    r.REVIEWER_NAME
  FROM #src_div s
  LEFT JOIN #dept_reviewer r
    ON r.DEPARTMENT_ID = s.DEPARTMENT_ID
) AS src
ON (
  tgt.UAR_PERIOD = src.UAR_PERIOD
  AND tgt.APPLICATION_ID = src.APPLICATION_ID
  AND tgt.USERNAME = src.USERNAME
  AND tgt.ROLE_ID = src.ROLE_ID
)
WHEN NOT MATCHED THEN
  INSERT (
    UAR_PERIOD, UAR_ID, USERNAME, ROLE_ID, APPLICATION_ID,
    DIVISION_ID, DEPARTMENT_ID, NOREG, NAME, POSITION_NAME, SECTION_ID,
    REVIEW_STATUS, DIV_APPROVAL_STATUS, SO_APPROVAL_STATUS,
    REVIEWER_NOREG, REVIEWER_NAME,
    CREATED_BY, CREATED_DT
  )
  VALUES (
    src.UAR_PERIOD, src.UAR_ID, src.USERNAME, src.ROLE_ID, src.APPLICATION_ID,
    src.DIVISION_ID, src.DEPARTMENT_ID, COALESCE(src.NOREG, 'UNKNOWN'), src.NAME, src.POSITION_NAME, src.SECTION_ID,
    NULL, NULL, NULL,
    src.REVIEWER_NOREG, src.REVIEWER_NAME,
    @CREATED_BY, GETDATE()
  )
WHEN MATCHED THEN
  UPDATE SET
    tgt.UAR_ID           = src.UAR_ID,
    tgt.DIVISION_ID      = src.DIVISION_ID,
    tgt.DEPARTMENT_ID    = COALESCE(tgt.DEPARTMENT_ID, src.DEPARTMENT_ID),
    tgt.NAME             = src.NAME,
    tgt.POSITION_NAME    = src.POSITION_NAME,
    tgt.SECTION_ID       = src.SECTION_ID,
    tgt.REVIEWER_NOREG   = COALESCE(src.REVIEWER_NOREG, tgt.REVIEWER_NOREG),
    tgt.REVIEWER_NAME    = COALESCE(src.REVIEWER_NAME,  tgt.REVIEWER_NAME),
    tgt.CHANGED_BY       = @CREATED_BY,
    tgt.CHANGED_DT       = GETDATE()
OUTPUT $action INTO @chg;

-- =========================
-- Cleanup & hasil
-- =========================
DROP TABLE IF EXISTS #div_approver;
DROP TABLE IF EXISTS #dept_reviewer;
DROP TABLE IF EXISTS #DVH_CODES;
DROP TABLE IF EXISTS #DPH_CODES;
DROP TABLE IF EXISTS #src_div;

SELECT
  SUM(CASE WHEN action='INSERT' THEN 1 ELSE 0 END) AS inserted,
  SUM(CASE WHEN action='UPDATE' THEN 1 ELSE 0 END) AS updated
FROM @chg;`;

  return rows?.[0] ?? { inserted: 0, updated: 0 };
}


/**
 * SYSTEM OWNER:
 * - Sumber: TB_M_AUTH_MAPPING (NOREG kosong/all-zero)
 * - Step: INSERT/UPSERT ke TB_R_WORKFLOW (SEQ_NO = 2) -> MERGE ke TB_R_UAR_SYSTEM_OWNER
 */
async function mergeSystemOwnerTx(tx: TxLike, p: GenParams): Promise<MergeCount> {
  const rows = await tx.$queryRaw<{ inserted: number; updated: number }[]>`
DECLARE @PERIOD_RAW NVARCHAR(30) = ${p.period};
DECLARE @APP_ID     NVARCHAR(50) = ${p.application_id};
DECLARE @CREATED_BY VARCHAR(50)  = ${p.createdBy};

-- Normalisasi UAR_PERIOD => YYYYMM
DECLARE @UAR_PERIOD CHAR(6);
IF @PERIOD_RAW LIKE '[0-9][0-9][0-9][0-9][0-9][0-9]' BEGIN
  SET @UAR_PERIOD = @PERIOD_RAW;
END ELSE BEGIN
  DECLARE @RUN_DATE DATE = TRY_CONVERT(DATE, @PERIOD_RAW, 126);
  IF @RUN_DATE IS NULL SET @RUN_DATE = TRY_CONVERT(DATE, @PERIOD_RAW);
  IF @RUN_DATE IS NULL THROW 50000, 'Invalid period. Use YYYYMM or ISO date (YYYY-MM-DD).', 1;
  SET @UAR_PERIOD = LEFT(CONVERT(CHAR(8), @RUN_DATE, 112), 6);
END

DECLARE @UYM CHAR(4) = RIGHT(@UAR_PERIOD, 4);
DECLARE @chg TABLE (action NVARCHAR(10));

IF OBJECT_ID('tempdb..#src_so') IS NOT NULL DROP TABLE #src_so;

-- Sumber SO: user AUTH_MAPPING yang NOREG-nya kosong, ambil posisi/section kalau ada (LEFT JOIN)
SELECT
  @UAR_PERIOD AS UAR_PERIOD,
  CONCAT('UAR_', @UYM, '_', am.APPLICATION_ID) AS UAR_ID,
  am.USERNAME,
  am.ROLE_ID,
  am.APPLICATION_ID,
  app.DIVISION_ID_OWNER AS DIVISION_ID,
  app.DIVISION_ID_OWNER AS DEPARTMENT_ID,
  NULLIF(LTRIM(RTRIM(am.NOREG)), '') AS NOREG,
  LTRIM(RTRIM(CONCAT(COALESCE(am.FIRST_NAME,''),' ',COALESCE(am.LAST_NAME,'')))) AS NAME,
  emp.POSITION_NAME AS POSITION_NAME,
  emp.SECTION_ID    AS SECTION_ID,
  am.COMPANY_CD,
  app.NOREG_SYSTEM_OWNER           AS REVIEWER_NOREG,
  so.PERSONNEL_NAME                AS REVIEWER_NAME   -- ambil nama SO dari employee
INTO #src_so
FROM TB_M_AUTH_MAPPING am
JOIN TB_M_APPLICATION  app ON app.APPLICATION_ID = am.APPLICATION_ID
LEFT JOIN TB_M_EMPLOYEE emp ON emp.NOREG = am.NOREG                 -- bisa NULL (memang target NOREG kosong)
LEFT JOIN TB_M_EMPLOYEE so  ON so.NOREG = app.NOREG_SYSTEM_OWNER     -- nama SO
WHERE am.APPLICATION_ID = @APP_ID
  AND (
    am.NOREG IS NULL
    OR LTRIM(RTRIM(am.NOREG)) = ''
    OR REPLACE(LTRIM(RTRIM(am.NOREG)), '0', '') = ''
  );

-- (1) UPSERT WORKFLOW SEQ 2 (System Owner)
MERGE TB_R_WORKFLOW AS wf
USING (
  SELECT UAR_ID, DIVISION_ID, DEPARTMENT_ID, REVIEWER_NOREG, REVIEWER_NAME FROM #src_so
) AS x
ON (wf.UAR_ID = x.UAR_ID AND wf.SEQ_NO = 2)
WHEN NOT MATCHED THEN
  INSERT (
    UAR_ID, SEQ_NO,
    DIVISION_ID, DEPARTMENT_ID,
    APPROVAL_CD, APPROVAL_DESC,
    APPROVER_NOREG, APPROVER_NAME,
    PLAN_APPROVED_DT, APPROVED_BY, APPROVED_DT,
    IS_APPROVED, IS_REJECTED,
    CREATED_BY, CREATED_DT
  )
  VALUES (
    x.UAR_ID, 2,
    x.DIVISION_ID, x.DEPARTMENT_ID,
    2, 'System Owner Approval',
    x.REVIEWER_NOREG, x.REVIEWER_NAME,
    NULL, NULL, NULL,
    0, 0,
    @CREATED_BY, GETDATE()
  )
WHEN MATCHED THEN
  UPDATE SET
    wf.DIVISION_ID    = x.DIVISION_ID,
    wf.DEPARTMENT_ID  = x.DEPARTMENT_ID,
    wf.APPROVER_NOREG = x.REVIEWER_NOREG,
    wf.APPROVER_NAME  = x.REVIEWER_NAME,
    wf.CHANGED_BY     = @CREATED_BY,
    wf.CHANGED_DT     = GETDATE();

-- (2) MERGE ke UAR_SYSTEM_OWNER  (struktur mirip Division User: kolom & values sejajar)
MERGE TB_R_UAR_SYSTEM_OWNER AS tgt
USING #src_so AS src
ON (
  tgt.UAR_PERIOD = src.UAR_PERIOD
  AND tgt.APPLICATION_ID = src.APPLICATION_ID
  AND tgt.USERNAME = src.USERNAME
  AND tgt.ROLE_ID = src.ROLE_ID
)
WHEN NOT MATCHED THEN
  INSERT (
    UAR_PERIOD, UAR_ID, USERNAME, ROLE_ID, APPLICATION_ID,
    DIVISION_ID, DEPARTMENT_ID, NOREG, NAME, POSITION_NAME, SECTION_ID,
    REVIEW_STATUS, SO_APPROVAL_STATUS,
    REVIEWER_NOREG, REVIEWER_NAME,
    CREATED_BY, CREATED_DT
  )
  VALUES (
    src.UAR_PERIOD, src.UAR_ID, src.USERNAME, src.ROLE_ID, src.APPLICATION_ID,
    src.DIVISION_ID, src.DEPARTMENT_ID, COALESCE(src.NOREG, 'UNKNOWN'), src.NAME, src.POSITION_NAME, src.SECTION_ID,
    NULL, NULL,
    src.REVIEWER_NOREG, src.REVIEWER_NAME,
    @CREATED_BY, GETDATE()
  )
WHEN MATCHED THEN
  UPDATE SET
    tgt.UAR_ID           = src.UAR_ID,
    tgt.DIVISION_ID      = src.DIVISION_ID,
    tgt.DEPARTMENT_ID    = COALESCE(tgt.DEPARTMENT_ID, src.DEPARTMENT_ID),
    tgt.NAME             = src.NAME,
    tgt.POSITION_NAME    = src.POSITION_NAME,
    tgt.SECTION_ID       = src.SECTION_ID,
    tgt.REVIEWER_NOREG   = COALESCE(src.REVIEWER_NOREG, tgt.REVIEWER_NOREG),
    tgt.REVIEWER_NAME    = COALESCE(src.REVIEWER_NAME,  tgt.REVIEWER_NAME),
    tgt.CHANGED_BY       = @CREATED_BY,
    tgt.CHANGED_DT       = GETDATE()
OUTPUT $action INTO @chg;

DROP TABLE #src_so;

SELECT
  SUM(CASE WHEN action='INSERT' THEN 1 ELSE 0 END) AS inserted,
  SUM(CASE WHEN action='UPDATE' THEN 1 ELSE 0 END) AS updated
FROM @chg;`;

  return rows?.[0] ?? { inserted: 0, updated: 0 };
}

export const uarGenerateRepository = {
  async generateAll(p: GenParams) {
    return prisma.$transaction(async (tx) => {
      const divisionUser = await mergeDivisionUserTx(tx, p);
      const systemOwner = await mergeSystemOwnerTx(tx, p);
      return { divisionUser, systemOwner };
    });
  },
};
