export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH-ERR-001',
  AUTH_SESSION_EXPIRED: 'AUTH-ERR-002',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH-ERR-003',
  AUTH_ACCOUNT_LOCKED: 'AUTH-ERR-004',
  AUTH_TOKEN_INVALID: 'AUTH-ERR-005',

  VAL_REQUIRED_FIELD: 'VAL-ERR-301',
  VAL_INVALID_FORMAT: 'VAL-ERR-302',

  API_NETWORK_ERROR: 'API-ERR-401',
  API_TIMEOUT: 'API-ERR-402',
  API_SERVER_ERROR: 'API-ERR-403',
  API_RATE_LIMIT: 'API-ERR-404',
  API_UNAUTHORIZED: 'API-ERR-405',

  SYS_UNKNOWN_ERROR: 'SYS-ERR-501',
  SYS_CONFIG_ERROR: 'SYS-ERR-502',
  SYS_DATABASE_ERROR: 'SYS-ERR-503',
  SYS_PERMISSION_DENIED: 'SYS-ERR-504'
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
