export const SECURITY_CONFIG = {
  SESSION_TIMEOUT_MS: 30 * 60 * 1000,
  SESSION_WARNING_MS: 5 * 60 * 1000,
  TOKEN_REFRESH_THRESHOLD_MS: 5 * 60 * 1000,
  MAX_SESSION_DURATION_MS: 8 * 60 * 60 * 1000,

  // total maximal login
  MAX_LOGIN_ATTEMPTS: 5,

  // total duration locked
  LOCKOUT_DURATION_MS: 0.2 * 60 * 1000,
  PASSWORD_MAX_AGE_DAYS: Number(process.env.PASSWORD_MAX_AGE_DAYS ?? 90),
  PASSWORD_EXPIRY_WARNING_DAYS: Number(process.env.PASSWORD_EXPIRY_WARNING_DAYS ?? 7),

  MAX_API_CALLS_PER_MINUTE: 60
} as const;
